### ISSUE TITLE
AttributeError: 'AWSRequestsAuth' object has no attribute 'split'

### ISSUE THREAD

**Issue by fiunchinho** [DavidMuller/aws-requests-auth#15]
Can't get this to work. Trying the README example I get the following error

```
AttributeError: 'AWSRequestsAuth' object has no attribute 'split'
```

Seems like both `Urllib3HttpConnection` and `RequestsHttpConnection` require http_auth to be either ':' separated string or a tuple. Any ideas?

**Comment by DavidMuller** [comment]
Someone emailed me with a similar issue a week or 2 ago. They were able to resolve their issues by upgrading their pip reqs: `aws-requests-auth` and `elasticsearch`.  

For what it's worth, we connect to our AWS Elasticsearch 1.5.X cluster using the following: 

```
aws-requests-auth==0.2.5
elasticsearch==1.7.0
```

What versions are you using?

**Comment by fiunchinho** [comment]
Sorry, I was using this library inside another project with its own requirements.txt file, so I didn't have the right versions.
