### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by natefox** [DavidMuller/aws-requests-auth#18]
Just wanted to thank you for your work with this module. This saved me quite a bit of time and effort.

FWIW (if you want to note in the readme), when using Lambda to access AWS ES, you can simply use the environment variables and therefore the role that Lambda is assuming:

```
import os
from aws_requests_auth.aws_auth import AWSRequestsAuth
from elasticsearch import Elasticsearch, RequestsHttpConnection

def lambda_handler(event, context):
    other_code_here()
    auth = AWSRequestsAuth(aws_access_key=os.environ['AWS_ACCESS_KEY_ID'],
                           aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'],
                           aws_token=os.environ['AWS_SESSION_TOKEN'],
                           aws_host=es_host,
                           aws_region='us-west-2',
                           aws_service='es')
```

**Comment by DavidMuller** [comment]
Thanks for reaching out @natefox -- I agree, that's a handy example to help people get started

I added a section called, "AWS Lambda Quickstart Example" to the end of the README in this commit: https://github.com/DavidMuller/aws-requests-auth/commit/07580bb32853bcc94b8fafce625e8c07a22cbfad
