### ISSUE TITLE
Issue with Python 3.6

### ISSUE THREAD

**Issue by hzainuddin2002** [DavidMuller/aws-requests-auth#19]
Getting TypeError: unicode-objects must be encoded before hashing. I believe its something to do with line. 
I know you're using the aws signed example
`payload_hash = hashlib.sha256(body).hexdigest()`

Was hoping you knew of a way to encode the body.

**Comment by hzainuddin2002** [comment]
`payload_hash = hashlib.sha256(body.encode(utf-8).hexdigest()` did the trick

**Comment by DavidMuller** [comment]
I have to confess that we still run a python 2.7.X environment in production, but I think @medwig fixed this issue in https://github.com/DavidMuller/aws-requests-auth/pull/21

Feel free to reopen this issue if the problem still appears
