### ISSUE TITLE
must be str, not NoneType: TypeError

### ISSUE THREAD

**Issue by MartinThoma** [DavidMuller/aws-requests-auth#34]
I tried "Using Boto To Automatically Gather AWS Credentials" and get:

    File "/var/task/aws_requests_auth/aws_auth.py", line 165, in get_aws_request_headers
    self.service)
    File "/var/task/aws_requests_auth/aws_auth.py", line 27, in getSignatureKey
    kDate = sign(('AWS4' + key).encode('utf-8'), dateStamp)
    TypeError: must be str, not NoneType

**Comment by MartinThoma** [comment]
Aparently the `key` is none.

**Comment by DavidMuller** [comment]
If you are using the `BotoAWSRequestsAuth` util, you'll also need to be sure that [boto3 is able to find credentials somewhere on your machine](http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials).
