### ISSUE TITLE
Is it working for awis API?

### ISSUE THREAD

**Issue by ebuildy** [DavidMuller/aws-requests-auth#36]
Trying with Python 3.6, and version 0.4.1:

```
import requests
from aws_requests_auth.aws_auth import AWSRequestsAuth

# let's talk to our AWS Elasticsearch cluster
auth = AWSRequestsAuth(aws_access_key='****',
                       aws_secret_access_key='****',
                       aws_host='awis.us-west-1.amazonaws.com',
                       aws_region='us-west-1',
                       aws_service='awis')

r = requests.get('https://awis.amazonaws.com/api?Action=CategoryListings&Count=10&Path=Top/Arts', auth=auth)
````

I got

```
The request signature we calculated does not match the signature you provided.
```

whereas it's working fine with another library. I missed something?

**Comment by DavidMuller** [comment]
Ah -- despite its generic name, `aws-requests-auth` was only really tested + built for use with AWS's Elasticserach service. It would not surprise me if it doesn't quite work with some of the other services as of right now

PRs, of course, are welcome if you see what is messing up the signature in this case (my guess is it has to do with this library's handling of url query params)

Another request signing library to give a shot might be https://github.com/sam-washington/requests-aws4auth

**Comment by ebuildy** [comment]
ha ok I see,

no problem, thanks you.
