### ISSUE TITLE
ImportError: cannot import name 'BotoAWSRequestsAuth'

### ISSUE THREAD

**Issue by john-aws** [DavidMuller/aws-requests-auth#39]
I note the comment in the README that botocore must be installed in order to import BotoAWSRequestsAuth but with the current version of botocore, aws-requests-auth, and Python 3.6.4, this import fails with ImportError: cannot import name 'BotoAWSRequestsAuth'.

I have:
```
aws-requests-auth==0.3.3
boto3==1.7.83
botocore==1.10.83

```
My Python script is:

```
import requests
from aws_requests_auth.boto_utils import BotoAWSRequestsAuth

```

**Comment by DavidMuller** [comment]
Hi @john-aws -- could you try with the latest release of `aws-requests-auth`? I'm not getting an `ImportError` with `aws-requests-auth==0.4.2` on Python `3.6`:

```bash
david@Davids-MBP ~ $ pip freeze | grep boto
boto3==1.7.83
botocore==1.10.83
david@Davids-MBP ~ $ pip freeze | grep aws-requests-auth
aws-requests-auth==0.4.2
david@Davids-MBP ~ $ python
Python 3.6.5 (default, Aug 17 2018, 18:12:21) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
>>> from aws_requests_auth.boto_utils import BotoAWSRequestsAuth
>>> 
```

**Comment by john-aws** [comment]
Hi, yes this solved the problem and apologies for not recognizing the back-level package number.

Thank you for the quick response.
