### ISSUE TITLE
request date Header may be upper case?

### ISSUE THREAD

**Issue by barryz** [DavidMuller/aws-requests-auth#41]
From the [aws offical documentation](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) I saw the header name  `X-Amz-Date` is uppercase with every first letter. 

But in your code, the header is `x-amz-date` .

**Comment by pghole** [comment]
@barryz I have same question. Why is that so ? https://github.com/DavidMuller/aws-requests-auth/blob/master/aws_requests_auth/aws_auth.py#L182
@DavidMuller ^^
