### ISSUE TITLE
integration with aiohttp

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [DavidMuller/aws-requests-auth#53]
I'm switching some of my HTTP calls from `requests` to `aiohttp` which uses [BasicAuth](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.BasicAuth) - is there any way of using this library with `aiohttp`?

**Comment by DavidMuller** [comment]
This package targets `requests` specifically - indeed `AWSRequestsAuth` inherits from [`requests.auth.AuthBase`](https://requests.readthedocs.io/en/master/user/authentication/#new-forms-of-authentication). No current public interfaces that work with other packages

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Alrighty thanks!

BTW the link to the `requests` package in the README is bad.
