### ISSUE TITLE
Posting Data 

### ISSUE THREAD

**Issue by KhushC-03** [DavidMuller/aws-requests-auth#58]
How would I use this to post JSON data?

    auth = AWSRequestsAuth(aws_access_key=access_key,
                           aws_secret_access_key=secret_key,
                           aws_token=security_token,
                           aws_host='g1ik5r2vf5.execute-api.eu-west-1.amazonaws.com',
                           aws_region='eu-west-1',
                           aws_service='execute-api')
g = v.post('',headers=entry_headers, json=entry_data, auth=auth, verify=True)

**Comment by naveenmarthala** [comment]
mr @KhushC-03 , you have closed the issue, so, i presume you have figured out a way to post json data? if yes, please comment how.
